### ISSUE TITLE
__iter__ and __getattr__

### ISSUE THREAD

**Issue by dseuss** [dseuss/mpnum#14]
The current behaviour might lead to some unexpected results, such as the following. Define

```
y = np.random.randn(1)
x = random_mpa(4, 2 ,1)
```

Then, `y[0] * x` gives a numpy array (since the numpy's multiplication with an iterator has precedence), but `x * y[0]` is an MPArray.

Ideas:
- create view objects for local tensors and physical tensor
- don't provide **iter**
- let getattr of a tuple (or a single number) return partial MPAs

**Comment by milan-hl** [comment]
Another possible alternative seems to be to define MPArray.__numpy_ufunc__ which can handle both cases:

http://docs.scipy.org/doc/numpy/neps/ufunc-overrides.html

http://docs.scipy.org/doc/numpy-1.11.0/reference/arrays.classes.html#numpy.class.__numpy_ufunc__ (seems to be now in numpy 1.11)

Excerpt from the first link:

```python
class MyObject(object):
    def __numpy_ufunc__(self, *a, **kw):
        return "ufunc"
    def __mul__(self, other):
        return 1234
    def __rmul__(self, other):
        return 4321

a = MyObject()
b = np.array([0])

a * b    # == 1234       OK
b * a    # == "ufunc"    surprising
```

However, I do like the idea to remove `MPArray.__iter__()` and maybe also `MPArray.__getitem__()` and replace them e.g. by `iter(mpa.sites)`, `mpa.sites[2:4]` and `mpa.phys[1, 0, 1]`.

**Comment by dseuss** [comment]
@milan-hl Agree?

**Comment by dseuss** [comment]
Alright, a first outline for this is in the brach `feat-ltensiter`. However, I did not manage to convert the `mpnum.linalg.mineig` routine, so the correponding [te](https://github.com/dseuss/mpnum/blob/feat-ltensiter/tests/linalg_test.py#L18)[sts](https://github.com/dseuss/mpnum/blob/feat-ltensiter/tests/linalg_test.py#L18) are currently deactiveated.

**Comment by dseuss** [comment]
Looks like we are happy with the changes. But we should keep the possible implications for laziness and the `copy` method in mind.
