### ISSUE TITLE
Numerical accuracy

### ISSUE THREAD

**Issue by dseuss** [dseuss/mpnum#2]
Compression tests fail randomly for different instances.

- Is the assert_mpa_identical too strict?
- We should check seeding since this is not reproducible.

**Comment by milan-hl** [comment]
Apparently we have another test which sometimes fails but sometimes does not:

https://travis-ci.org/dseuss/mpnum/jobs/126319313


```
=================================== FAILURES ===================================
_____________________ [doctest] mpnum.factory.random_mpdo ______________________
290     :returns: randomly choosen matrix product (pure) state
291 
292     >>> rho = random_mpdo(4, 2, 4)
293     >>> rho.bdims, rho.pdims
294     ((4, 4, 4), ((2, 2), (2, 2), (2, 2), (2, 2)))
295     >>> rho.normal_form
296     (0, 4)
297     >>> rho_dense = rho.to_array_global().reshape((2**4,) * 2)
298     >>> from numpy.linalg import eigvals
299     >>> min(eigvals(rho_dense)) >= -1e-14
Expected:
    True
Got:
    False
```

vs.

https://travis-ci.org/dseuss/mpnum/jobs/126319278 (1 unrelated commit earlier, all good)
https://travis-ci.org/dseuss/mpnum/jobs/126640751 (1 unrelated commit later, all good)

**Comment by dseuss** [comment]
I guess 10^-14 is too strict. I think the eigvals function uses a random initialisation, which could explain the random failure behaviour

**Comment by milan-hl** [comment]
Unfortunately, another possibly accuracy-related error occured on the last commit:

https://travis-ci.org/dseuss/mpnum/jobs/126667266
