### ISSUE TITLE
inner() is inconsistent with numpy

### ISSUE THREAD

**Issue by milan-hl** [dseuss/mpnum#22]
numpy behaivour:

```python
>>> import numpy as np
>>> u = np.array([1j, 0])
>>> v = np.array([1, 0])
>>> np.inner(u, v)
1j
```

`inner()` does not complex-conjugate the first argument. In mpnum, it does:

```python
>>> import mpnum as mp
>>> mpu = mp.MPArray.from_array(u, plegs=1)
>>> mpv = mp.MPArray.from_array(v, plegs=1)
>>> mp.inner(mpu, mpv)
array(-1j)
```

This is not consistent with numpy. Is this desirable? 

In numpy, there is also `vdot()`, which complex-conjugates its first argument:

```python
>>> np.dot(u, v)
1j
>>> np.vdot(u, v)
-1j
>>> mp.dot(mpu, mpv).to_array()
array(1j)
```

**Comment by dseuss** [comment]
Yes, this is on purpose. `inner` provides the inner product of the given vector space -- and this should include conjugation (in one argument). For everything else, just use `dot`

**Comment by dseuss** [comment]
@milan-hl Happy? Agreeing?

**Comment by milan-hl** [comment]
I still don't like the fact that naming is different from numpy, but I'm fine with the way it is, it makes sense.
