### ISSUE TITLE
Link to source code on readthedocs

### ISSUE THREAD

**Issue by milan-hl** [dseuss/mpnum#50]
Add links to source code on readthedocs -- how this can be achieved is described at https://github.com/rtfd/readthedocs.org/issues/2139#issuecomment-352188629.

**Comment by dseuss** [comment]
Looks good, someone has to do it of course 👍

**Comment by milan-hl** [comment]
Fixed in 5eb91a9fb38669bc51e84dd38fa8664e3a713521
