### ISSUE TITLE
mpnum for windows

### ISSUE THREAD

**Issue by gharib85** [dseuss/mpnum#53]
i am trying to use mpnum on windows 
i wish if any help to install mpnum window

**Comment by dseuss** [comment]
I'll need some more information to be able to help you: How are you using python on Windows (e.g. using conda)? 

Generally, mpnum should work without any issues on windows as it's pure python and doesn't have any compiled compontents.

**Comment by gharib85** [comment]
thanks so much for u interest 
i installed it successfully

**Comment by dseuss** [comment]
No worries.
